### ISSUE TITLE
[Question] Possibility of exposing the db as an API?

### ISSUE THREAD

**Issue by dbetteridge** [kronicd/WA_Covid_Mailer#3]
Possibility of exposing the db you're using for emails as an API?

Wanted to try and knock up a slightly more user friendly site for the data and an API would be a great way to just stand up a netlify/github pages/serverless frontend.

Obviously understand if you're looking to keep it lean and low cost, in which case i'll just stand up a server 😁

**Comment by kronicd** [comment]
What sort of functionality are you after from an API?

I could easily enough provide a continuously updated json dump of the db if that would suit your application.

**Comment by dbetteridge** [comment]
Pretty much exactly that, dump of the exposure sites as a json response, were you thinking dump to a file somewhere? Or just on a /api/sites type thing

**Comment by kronicd** [comment]
I can just drop it to /dump.json (or similar) on the site. I'll update and close this issue once I've added that, I should be able to get to it in the next couple of days.

Cheers!

**Comment by kronicd** [comment]
Heyhey, the DB is now being dumped to json at `https://exposures.kronicd.net/exposures.json` hourly.

There are also some additional changes coming to integrate multiple additional data sources. Just waiting to finish testing.
